from enum import Enum


class AgentIntent(str, Enum):
    LMS_PROFILE = "LMS_PROFILE"
    LMS_PROGRESS = "LMS_PROGRESS"
    LMS_ASSESSMENT = "LMS_ASSESSMENT"
    CONTENT_SEARCH = "CONTENT_SEARCH"
    PLAYLIST_SEARCH = "PLAYLIST_SEARCH"
    CONTENT_DETAIL = "CONTENT_DETAIL"
    PLAYLIST_DETAIL = "PLAYLIST_DETAIL"
    RECOMMENDATION = "RECOMMENDATION"
    PDF_KNOWLEDGE = "PDF_KNOWLEDGE"
    VIDEO_KNOWLEDGE = "VIDEO_KNOWLEDGE"
    GENERAL_LMS = "GENERAL_LMS"
    GENERAL_CHAT = "GENERAL_CHAT"
